### ISSUE TITLE
PostgreSQL versions prior to 9.5 are not supported

### ISSUE THREAD

**Issue by kenny-evitt** [darinwilson/music_db_workshop#10]
I'm getting an error running the *bin/setup* script:

```
...

15:50:09.435 [debug] QUERY ERROR db=0.0ms queue=6.3ms
INSERT INTO "genres" ("name","wiki_tag","inserted_at","updated_at") VALUES ($1,$2,$3,$4) ON CONFLICT ("name") DO UPDATE SET "name" = EXCLUDED."name","wiki_tag" = EXCLUDED."wiki_tag","inserted_at" = EXCLUDED."inserted_at","updated_at" = EXCLUDED."updated_at" RETURNING "id" ["jazz", "Jazz", ~N[2019-08-22 19:50:09], ~N[2019-08-22 19:50:09]]
** (Postgrex.Error) ERROR 42601 (syntax_error) syntax error at or near "ON"

    query: INSERT INTO "genres" ("name","wiki_tag","inserted_at","updated_at") VALUES ($1,$2,$3,$4) ON CONFLICT ("name") DO UPDATE SET "name" = EXCLUDED."name","wiki_tag" = EXCLUDED."wiki_tag","inserted_at" = EXCLUDED."inserted_at","updated_at" = EXCLUDED."updated_at" RETURNING "id"
    (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto) lib/ecto/repo/schema.ex:649: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:164: Ecto.Repo.Schema.insert!/4
    priv/repo/seeds.exs:4: (file)
Unable to setup the database - please check the settings in config/dev.exs
```

The error seems to be due to the `ON CONFLICT` clause in the SQL command being executed and that makes sense as I'm running PostgreSQL 9.4.5:

```
✘-1 ~/@code/music_db_workshop [master ↑·1|…1] 
(ins)15:50 $ psql -d postgres
psql (9.4.5)
Type "help" for help.

(ins)postgres=# SELECT version();
                                                   version                                                    
--------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.5 on x86_64-apple-darwin15.0.0, compiled by Apple LLVM version 7.0.0 (clang-700.1.76), 64-bit
(1 row)
```

... and that clause doesn't seem to be supported in 9.4.*x* versions:

 - [PostgreSQL: Documentation: 9.4: INSERT](https://www.postgresql.org/docs/9.4/sql-insert.html)

It does seem supported in versions since 9.5 tho:

 - [`ON CONFLICT` Clause – PostgreSQL: Documentation: 9.5: INSERT](https://www.postgresql.org/docs/9.5/sql-insert.html#SQL-ON-CONFLICT)

The simplest 'fix' would be to update the README to state that the prerequisite is "PostgreSQL >= 9.5".

**Comment by darinwilson** [comment]
Sorry you had trouble @kenny-evitt - thanks for letting us know about this and providing all the detail. 

PR #11 gets rid of the `on_conflict` calls - they weren't critical, and I just need to do a better job of making the setup script idempotent. 

Please let me know if you run into any more issues.

**Comment by kenny-evitt** [comment]
@darinwilson Thanks! And will do about any other issues.
